import { test, expect, type Page } from '@playwright/test'

// Critical backwards-compatibility: URLs generated by the old app must still work.
// These query params are part of the public URL contract — must not regress.

const TS = '1717156800'
const BASE = `/${TS}`

// On mobile the calendar section is behind a scroll hint.
async function revealCalendar(page: Page) {
  const hint = page.locator('.display-scroll-hint')
  try {
    await hint.waitFor({ state: 'visible', timeout: 1500 })
    await hint.click()
  } catch {
    // Desktop: scroll hint is CSS-hidden, cal-wrapper already accessible
  }
}

test('?name param shows add-to-calendar button', async ({ page }) => {
  await page.goto(`${BASE}?name=Test+Event`)
  await revealCalendar(page)
  await expect(page.locator('.cal-btn')).toBeVisible()
})

test('?name + ?description + ?location are all accepted', async ({ page }) => {
  await page.goto(`${BASE}?name=My+Event&description=A+test+event&location=Online`)
  await revealCalendar(page)
  await expect(page.locator('.cal-btn')).toBeVisible()
})

test('?enddate with valid 10-digit unix timestamp shows calendar button', async ({ page }) => {
  const endTs = String(Number(TS) + 3600)
  await page.goto(`${BASE}?name=My+Event&enddate=${endTs}`)
  await revealCalendar(page)
  await expect(page.locator('.cal-btn')).toBeVisible()
})

test('?enddate with non-10-digit value is silently ignored (name still shows button)', async ({ page }) => {
  await page.goto(`${BASE}?name=My+Event&enddate=12345`)
  await revealCalendar(page)
  // enddate is invalid so calEndTs is null, but name is present — button still shows
  await expect(page.locator('.cal-btn')).toBeVisible()
})

test('?enddate alone (no name) still shows calendar button', async ({ page }) => {
  const endTs = String(Number(TS) + 3600)
  await page.goto(`${BASE}?enddate=${endTs}`)
  await revealCalendar(page)
  await expect(page.locator('.cal-btn')).toBeVisible()
})

test('end time from ?enddate is included in calendar URL', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'mobile', 'dropdown unavailable on mobile')
  const endTs = String(Number(TS) + 3600) // 1h after start
  await page.goto(`${BASE}?name=Timed&enddate=${endTs}`)
  await page.locator('.cal-btn').click()
  const href = await page.locator('.cal-dropdown a').filter({ hasText: 'Google Calendar' }).getAttribute('href')
  // TS = 2024-05-31T12:00Z, endTs = 2024-05-31T13:00Z
  expect(href).toContain('20240531T120000Z')
  expect(href).toContain('20240531T130000Z')
})

test('unknown query params do not cause page errors', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (err) => errors.push(err.message))
  await page.goto(`${BASE}?unknown=value&foo=bar`)
  expect(errors).toHaveLength(0)
})
